---
- name: "Load lvm kernel modules"
  modprobe:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "dm_snapshot"
    - "dm_mirror"
    - "dm_thin_pool"

- name: "Install glusterfs mount utils (RedHat)"
  yum:
    name: "glusterfs-fuse"
    state: "present"
  when: "ansible_os_family == 'RedHat'"

- name: "Install glusterfs mount utils (Debian)"
  apt:
    name: "glusterfs-client"
    state: "present"
  when: "ansible_os_family == 'Debian'"
